#Tránh hard-code string. Giúp dễ bảo trì và tránh lỗi chính tả.

# --- ROLES ---
ROLE_CUSTOMER = "Customer"
ROLE_ADMIN = "ADMIN"
ROLE_LOCKED = "LOCKED"

# --- AUTH PROVIDERS ---
AUTH_PROVIDER_LOCAL = "LOCAL"
AUTH_PROVIDER_GOOGLE = "GOOGLE"

# --- ORDER STATUSES ---
ORDER_STATUS_PENDING = "Pending"
ORDER_STATUS_SHIPPING = "Processing"
ORDER_STATUS_DELIVERED = "Delivered"
ORDER_STATUS_CANCELLED = "Cancelled"

VALID_ORDER_STATUSES = [
    ORDER_STATUS_PENDING,
    ORDER_STATUS_SHIPPING,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELLED,
]

# Quy tắc chuyển trạng thái hợp lệ (state machine)
VALID_STATUS_TRANSITIONS = {
    ORDER_STATUS_PENDING: [ORDER_STATUS_SHIPPING, ORDER_STATUS_CANCELLED],
    ORDER_STATUS_SHIPPING: [ORDER_STATUS_DELIVERED, ORDER_STATUS_CANCELLED],
    ORDER_STATUS_DELIVERED: [],   # Đã giao xong, không cho đổi
    ORDER_STATUS_CANCELLED: [],   # Đã hủy, không cho đổi
}